---
title: "05a_Testes_soft_power_WGCNA.rmd"
author: "Garett Slater"
date: "April 21 2022"
output:
  html_document: default
  pdf_document: default
---

```{r knitr setup, include=FALSE,  eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(eval=TRUE, cache=FALSE, message=FALSE, warning=FALSE, 
                      comment = "")
```


```{r data}
library(WGCNA)
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
load( file = "T_datExpr.RData")
```

```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
####################
# Choose a set of soft threshold parameters
####################
powers = c(c(1:20), seq(from = 22, to=30, by=2))
T_sft = pickSoftThreshold(T_datExpr, powerVector = powers, verbose = 5) 

# Scale-free topology fit index as a function of the soft-thresholding power
pdf(file = "2-Testes-sft.pdf", width = 9, height = 5);
par(mfrow = c(1,2));
cex1 = 0.9;

plot(T_sft$fitIndices[,1], -sign(T_sft$fitIndices[,3])*T_sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(T_sft$fitIndices[,1], -sign(T_sft$fitIndices[,3])*T_sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");

# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red") 

# Mean connectivity as a function of the soft-thresholding power
plot(T_sft$fitIndices[,1], T_sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity")) 
text(T_sft$fitIndices[,1], T_sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
dev.off()

par(mfrow = c(1,2));
cex1 = 0.9;

plot(T_sft$fitIndices[,1], -sign(T_sft$fitIndices[,3])*T_sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(T_sft$fitIndices[,1], -sign(T_sft$fitIndices[,3])*T_sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");

# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red") 

# Mean connectivity as a function of the soft-thresholding power
plot(T_sft$fitIndices[,1], T_sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity")) 
text(T_sft$fitIndices[,1], T_sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
```


```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
T_net = blockwiseModules(T_datExpr, power = 6,
                       TOMType = "unsigned", networkType = "unsigned",
                       minModuleSize = 30,pamStage = TRUE,
                       reassignThreshold = 0, mergeCutHeight = 0.25,
                       numericLabels = TRUE, pamRespectsDendro = TRUE,
                       saveTOMs = TRUE,deepSplit = 2,
                       saveTOMFileBase = "Testes_TOM",
                       verbose = 3)

                    

# open a graphics window
sizeGrWindow(12, 9)
# Convert labels to colors for plotting
T_mergedColors = labels2colors(T_net$colors)
# Plot the dendrogram and the module colors underneath
pdf(file = "4-Testes-module_tree.pdf", width = 8, height = 6);
plotDendroAndColors(T_net$dendrograms[[1]], T_mergedColors[T_net$blockGenes[[1]]],
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
dev.off()



T_moduleLabels = T_net$colors
T_moduleColors = labels2colors(T_net$colors)
T_MEs = T_net$MEs;
T_geneTree = T_net$dendrograms[[1]];
save(T_MEs, T_moduleLabels, T_moduleColors, T_geneTree, T_net,T_mergedColors,T_sft,
     file = "Testes-networkConstruction-auto.RData")


```

```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
par(cex = 1.6);
par(mar = c(0,4,2,0))
plotDendroAndColors(T_net$dendrograms[[1]], T_mergedColors[T_net$blockGenes[[1]]],
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
```


```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
# It is often interesting to study the relationships among the found modules.
# One can use the eigengenes as representative profiles and quantify module similarity by eigengene correlation.

# Calculate eigengenes

T_MEList = moduleEigengenes(T_datExpr, T_moduleColors, excludeGrey = TRUE, softPower = 6)
MEs_T_plot = T_MEList$eigengenes

# Calculate dissimilarity of module eigengenes
T_MEDiss = 1-cor(MEs_T_plot);

# Cluster module eigengenes
T_METree = hclust(as.dist(T_MEDiss), method = "average");

# Plot the result

sizeGrWindow(12,12);

par(cex = 1.0)
pdf(file = "Testes-eigengenes_cluster.pdf", width = 12, height = 9);
plot(T_METree, main = "Clustering of module eigengenes D",
     xlab = "", sub = "")
dev.off()



# export lists of genes within each module of D
genes = colnames(T_datExpr)
for(color in 0:max(T_net$colors)){
  # save transcript ids in this module
  write.table( genes[ T_net$colors == color ],
               file=(paste("~/OneDrive/Manuscripts/GenesOfDrones/WGCNA/Module_T/",
                           color,".txt",sep="")),sep="\t",row.names=F,col.names=F,quote=F )
  
  plot(T_METree, main = "Clustering of module eigengenes D",
     xlab = "", sub = "")
}


# adjacency and connectivity

T_adj = adjacency(T_datExpr,
                  type = "unsigned",
                  power = 6)

save(T_adj, file = "T_adj.RData")

# Calculates intramodular connectivity, i.e., connectivity of nodes to other nodes within the same module.
T_Alldegrees = intramodularConnectivity(T_adj, T_moduleColors)
write.csv(T_Alldegrees, file = "T_Alldegrees.csv")

```

```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
par(cex = 1);
par(mar = c(0,4,2,0))
plot(T_METree, main = "Clustering of module eigengenes D",
     xlab = "", sub = "")
```



