---
title: "08b-Brain-HubGenes_Expression.rmd"
author: "Garett Slater"
date: "April 21 2022"
output:
  html_document: default
  pdf_document: default
---

```{r knitr setup, include=FALSE,  eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(eval=TRUE, cache=FALSE, message=FALSE, warning=FALSE, 
                      comment = "")
```


```{r echo=FALSE}
library(pacman)
p_load(readxl,dplyr,tidyverse,lme4,fmsb,WGCNA,ggpubr)
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
load(file="T_datExpr.RData")
load(file="B_datExpr.RData")
ID<-read_excel("~/OneDrive/Manuscripts/GenesOfDrones/Resources/Expression_Drone_Trait.xlsx",sheet="ID")
Sperm<-read_excel("~/OneDrive/Manuscripts/GenesOfDrones/Resources/Expression_Drone_Trait.xlsx",sheet="Sperm")
RFID_out<-read.csv("~/OneDrive/Manuscripts/GenesOfDrones/Resources/RFID_2020Final_out.csv")
Weight<-read_excel("~/OneDrive/Manuscripts/GenesOfDrones/Resources/Expression_Drone_Trait.xlsx",sheet="Weight")
Morpho<-read_excel("~/OneDrive/Manuscripts/GenesOfDrones/Resources/Expression_Drone_Trait.xlsx",sheet="Morpho")

#Summarized Flight Trait data
RFID_out<-merge(RFID_out,ID,by="UID")
RFID_out$UTCTime_Final<- with(RFID_out, as.POSIXct(paste(UTCDate, UTCTime), format="%m/%d/%Y %H:%M:%OS"))
var_out<-RFID_out %>% group_by(UID) %>% dplyr::summarise(N_flights=length(flight),mean_flight_timediff=mean(timediff)/60,first_flight_age=min(Drone_Age))
flight_1<-merge(var_out,ID,by="UID")
```
# Brain hub genes for Light Green and Tan consensus Module

Light Green
- GB51797
- GB16670
- GB52537
- GB48698

Pink
- GB53975
- GB53190
- GB51900
- GB53915

Salmon
- GB46222
- GB53622
- GB53621
- GB46954

Turquoise
- GB46263
- GB46627
- GB45042
- GB40361

# Light Green - GB51797
```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
x<-as.data.frame(B_datExpr)

Hub1_Red<-dplyr::select(x,"GB51797")
colnames(Hub1_Red)<-"GB"
Hub1_Red$ID2<-rownames(Hub1_Red)
Hub1_Red<-merge(SampleB,Hub1_Red,by="ID2")
Hub1_Red$phen_age<-as.character(Hub1_Red$phen_age)

ff<-Hub1_Red%>%group_by(Maturity)%>% dplyr::summarise(mean=mean(GB),sd=sd(GB),N=length(GB),se=sd/sqrt(N))

aov<-aov(GB~ Maturity, data=Hub1_Red)
summary(aov)

pdf(file = "LightGreen_HUBGene_GB51797.pdf", width = 12, height = 9);
sp<-ggplot(data=ff, aes(x=Maturity, y=mean)) +
  geom_point(position=position_dodge(.2)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=0,position=position_dodge(.2)) +
  xlab("Maturity") +
  ylab("fPKM") +
  ggtitle("GB51797")+
  scale_colour_hue(name="Tissue Type", l=40) + 
  theme_classic() + theme(axis.ticks.x = element_blank(),
                     axis.title.x = element_blank(),
                     axis.text.x   = element_text(size=10, color="black"),
                     axis.title.y  = element_text(face="bold", size=12),
                     axis.text.y   = element_text(size=10, color="black"),
                     legend.background = element_rect(size=0.5, linetype="solid",colour ="black"))
sp
dev.off()
sp
```



# Pink - GB53975
```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
x<-as.data.frame(B_datExpr)

Hub1_Red<-dplyr::select(x,"GB53975")
colnames(Hub1_Red)<-"GB"
Hub1_Red$ID2<-rownames(Hub1_Red)
Hub1_Red<-merge(SampleB,Hub1_Red,by="ID2")
Hub1_Red$phen_age<-as.character(Hub1_Red$phen_age)

aov<-aov(GB~ Maturity, data=Hub1_Red)
summary(aov)


ff<-Hub1_Red%>%group_by(Maturity)%>% dplyr::summarise(mean=mean(GB),sd=sd(GB),N=length(GB),se=sd/sqrt(N))

pdf(file = "Pink_HUBGene_GB53975.pdf", width = 12, height = 9);
sp<-ggplot(data=ff, aes(x=Maturity, y=mean)) +
  geom_point(position=position_dodge(.2)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=0,position=position_dodge(.2)) +
  xlab("Maturity") +
  ylab("fPKM") +
  ggtitle("GB53975")+
  scale_colour_hue(name="Tissue Type", l=40) + 
  theme_classic() + theme(axis.ticks.x = element_blank(),
                     axis.title.x = element_blank(),
                     axis.text.x   = element_text(size=10, color="black"),
                     axis.title.y  = element_text(face="bold", size=12),
                     axis.text.y   = element_text(size=10, color="black"),
                     legend.background = element_rect(size=0.5, linetype="solid",colour ="black"))
sp
dev.off()
sp

```
# Turquoise - GB46263
```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
x<-as.data.frame(B_datExpr)

Hub1_Red<-dplyr::select(x,"GB46263")
colnames(Hub1_Red)<-"GB"
Hub1_Red$ID2<-rownames(Hub1_Red)
Hub1_Red<-merge(SampleB,Hub1_Red,by="ID2")
Hub1_Red$phen_age<-as.character(Hub1_Red$phen_age)

aov<-aov(GB~ Maturity, data=Hub1_Red)
summary(aov)



ff<-Hub1_Red%>%group_by(Maturity)%>% dplyr::summarise(mean=mean(GB),sd=sd(GB),N=length(GB),se=sd/sqrt(N))

pdf(file = "Turquoise_Brain_HUBGene_GB46263.pdf", width = 12, height = 9);
sp<-ggplot(data=ff, aes(x=Maturity, y=mean)) +
  geom_point(position=position_dodge(.2)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=0,position=position_dodge(.2)) +
  xlab("Maturity") +
  ylab("fPKM") +
  ggtitle("GB46263")+
  scale_colour_hue(name="Tissue Type", l=40) + 
  theme_classic() + theme(axis.ticks.x = element_blank(),
                     axis.title.x = element_blank(),
                     axis.text.x   = element_text(size=10, color="black"),
                     axis.title.y  = element_text(face="bold", size=12),
                     axis.text.y   = element_text(size=10, color="black"),
                     legend.background = element_rect(size=0.5, linetype="solid",colour ="black"))
sp
dev.off()
sp

```

#  Maturity
```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")

#Flight
flight_1<-merge(var_out,ID,by="UID")
flight_1<-flight_1[which(flight_1$Maturity!="NA"),]
ff<-flight_1%>%group_by(Maturity)%>% dplyr::summarise(mean=mean(first_flight_age),sd=sd(first_flight_age),N=length(first_flight_age),se=sd/sqrt(N))

ff2<-flight_1%>%group_by(Maturity)%>% dplyr::summarise(mean=mean(mean_flight_timediff),sd=sd(mean_flight_timediff),N=length(mean_flight_timediff),se=sd/sqrt(N))

#Weight
morpho_1<-merge(Weight,ID)
ff3<-morpho_1%>%group_by(Maturity)%>% dplyr::summarise(mean=mean(Weight),sd=sd(Weight),N=length(Weight),se=sd/sqrt(N))

pdf(file = "Maturity_Traits.pdf", width = 12, height = 9);
sp<-ggplot(data=ff, aes(x=Maturity, y=mean)) + 
    geom_bar(stat="identity", width=.5,position=position_dodge()) + 
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1) +
    xlab("Maturity") +
    ylab("First Flight Age") +
    ggtitle("Maturity and First Flight Age")+
    theme_classic() +
    theme(axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x   = element_text(size=10, color="black"),
          axis.title.y  = element_text(face="bold", size=12),
          axis.text.y   = element_text(size=10, color="black"),
          legend.background = element_rect(size=0.5, linetype="solid",colour ="black")) 
  
sp1<-ggplot(data=ff2, aes(x=Maturity, y=mean)) + 
    geom_bar(stat="identity", width=.5,position=position_dodge()) + 
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1) +
    xlab("Maturity") +
    ylab("Fight Duration") +
    ggtitle("Maturity and Weight")+
    theme_classic() +
    theme(axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x   = element_text(size=10, color="black"),
          axis.title.y  = element_text(face="bold", size=12),
          axis.text.y   = element_text(size=10, color="black"),
          legend.background = element_rect(size=0.5, linetype="solid",colour ="black")) 

sp2<-ggplot(data=ff3, aes(x=Maturity, y=mean)) + 
    geom_bar(stat="identity", width=.5,position=position_dodge()) + 
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1) +
    xlab("Maturity") +
    ylab("First Flight Age") +
    ggtitle("Maturity and First Flight Age")+
    theme_classic() +
    theme(axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x   = element_text(size=10, color="black"),
          axis.title.y  = element_text(face="bold", size=12),
          axis.text.y   = element_text(size=10, color="black"),
          legend.background = element_rect(size=0.5, linetype="solid",colour ="black")) 

ggarrange(sp, sp1,sp2, ncol = 3, nrow = 1)
dev.off()
ggarrange(sp, sp1,sp2, ncol = 3, nrow = 1)


two.way <- aov(Weight ~ Maturity, data = morpho_1)
summary(two.way)

two.way <- aov(mean_flight_timediff ~ Maturity, data = flight_1)
summary(two.way)


```

# First Flight Age and Sperm Graphic
```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")

#Flight
flight_1<-merge(var_out,ID,by="UID")
flight_1<-merge(Sperm,flight_1)
flight_1<-flight_1[which(flight_1$Sperm_Conc_2<15),]
flight_1$phen_age<-as.character(flight_1$phen_age)

pdf(file = "Sperm_FirstFlightAge_Traits.pdf", width = 12, height = 9);
sp<-ggplot(flight_1,aes(first_flight_age,Sperm_Conc_2)) +
  geom_point() +
  geom_smooth(method='lm')+
  xlab("First Flight Age") +
    ylab("Sperm Concentration") +
    theme_classic() +
    theme(axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x   = element_text(size=10, color="black"),
          axis.title.y  = element_text(face="bold", size=12),
          axis.text.y   = element_text(size=10, color="black"),
          legend.background = element_rect(size=0.5, linetype="solid",colour ="black")) 
sp
dev.off()
sp


two.way <- lm(Sperm_Conc_2 ~ phen_age*first_flight_age, data = flight_1)
summary(two.way)
```
- GB46222
- GB53622
- GB53621
- GB46954



# Salmon - GB46222
```{r echo=FALSE}
setwd("~/OneDrive/Manuscripts/GenesofDrones/WGCNA")
x<-as.data.frame(B_datExpr)

Hub1_Red<-dplyr::select(x,"GB46222")
colnames(Hub1_Red)<-"GB"
Hub1_Red$ID2<-rownames(Hub1_Red)
Hub1_Red<-merge(SampleB,Hub1_Red,by="ID2")
Hub1_Red$phen_age<-as.character(Hub1_Red$phen_age)
Hub1_Red_2<-merge(Hub1_Red,Sperm)
Hub1_Red<-merge(Hub1_Red,var_out)
Hub1_Red<-Hub1_Red[which(Hub1_Red$GB<200),]
Hub1_Red_2<-Hub1_Red_2[which(Hub1_Red_2$GB<200),]
Hub1_Red_2<-Hub1_Red_2[which(Hub1_Red_2$Sperm_Conc_2<15),]

pdf(file = "Salmon_Brain_HUBGene_GB46222.pdf", width = 12, height = 9);
sp<-ggplot(Hub1_Red,aes(first_flight_age,GB)) +
  geom_point() +
  geom_smooth(method='lm')+
  xlab("First Flight Age") +
    ylab("GB") +
    theme_classic() +
    theme(axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x   = element_text(size=10, color="black"),
          axis.title.y  = element_text(face="bold", size=12),
          axis.text.y   = element_text(size=10, color="black"),
          legend.background = element_rect(size=0.5, linetype="solid",colour ="black")) 


sp2<-ggplot(Hub1_Red_2,aes(Sperm_Conc_2,GB)) +
  geom_point() +
  geom_smooth(method='lm')+
  xlab("Sperm Concentration") +
    ylab("GB") +
    theme_classic() +
    theme(axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x   = element_text(size=10, color="black"),
          axis.title.y  = element_text(face="bold", size=12),
          axis.text.y   = element_text(size=10, color="black"),
          legend.background = element_rect(size=0.5, linetype="solid",colour ="black")) 




ggarrange(sp,sp2, ncol = 2, nrow = 1)
dev.off()
ggarrange(sp,sp2, ncol = 2, nrow = 1)


two.way <- lm(GB ~ phen_age*first_flight_age, data = Hub1_Red)
summary(two.way)

two.way <- lm(GB ~ phen_age*Sperm_Conc_2, data = Hub1_Red_2)
summary(two.way)

```


